// web/src/features/map/map-view.tsx
import { Fragment, useMemo, useState } from "react";
import { Layers3, LocateFixed, MapPinned, Minus, Plus } from "lucide-react";
import { CRS, icon, type LatLngExpression } from "leaflet";
import {
  Circle,
  MapContainer,
  Marker,
  Popup,
  TileLayer,
  Tooltip,
  useMap,
  useMapEvents,
} from "react-leaflet";
import { useNavigate } from "react-router-dom";

import { StatusDot } from "@/components/common/status-dot";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Label } from "@/components/ui/label";
import {
  useGuilds,
  useOnlinePlayers,
  useServerInfo,
} from "@/hooks/use-server-data";
import { formatCoordinate } from "@/lib/format";
import { useI18n } from "@/lib/i18n";

import baseIconUrl from "@/assets/map/base.webp";
import bossTowerIconUrl from "@/assets/map/boss_tower.webp";
import fastTravelIconUrl from "@/assets/map/fast_travel.webp";
import playerIconUrl from "@/assets/map/player.webp";
import pointsJson from "@/assets/map/points.json";

const LANDSCAPE = {
  maxX: 349_400,
  maxY: 724_400,
  minX: -1_099_400,
  minY: -724_400,
};
const MAP_SIZE = 512;

const points = pointsJson as {
  boss_tower: [number, number][];
  fast_travel: [number, number][];
};

function toMapPosition(position: [number, number]): LatLngExpression {
  const latitude =
    -MAP_SIZE +
    (MAP_SIZE * (position[0] - LANDSCAPE.minX)) /
      (LANDSCAPE.maxX - LANDSCAPE.minX);
  const longitude =
    (MAP_SIZE * (position[1] - LANDSCAPE.minY)) /
    (LANDSCAPE.maxY - LANDSCAPE.minY);
  return [latitude, longitude];
}

function fromMapPosition(position: [number, number]) {
  const x =
    ((position[0] + MAP_SIZE) * (LANDSCAPE.maxX - LANDSCAPE.minX)) / MAP_SIZE +
    LANDSCAPE.minX;
  const y =
    (position[1] * (LANDSCAPE.maxY - LANDSCAPE.minY)) / MAP_SIZE +
    LANDSCAPE.minY;
  return [Math.round(x), Math.round(y)] as const;
}

function toMapDistance(distance: number) {
  return MAP_SIZE * (distance / (LANDSCAPE.maxX - LANDSCAPE.minX));
}

function CoordinateTracker({
  onMove,
}: {
  onMove: (position: readonly [number, number]) => void;
}) {
  useMapEvents({
    mousemove(event) {
      onMove(fromMapPosition([event.latlng.lat, event.latlng.lng]));
    },
  });
  return null;
}

function MapZoomControls() {
  const { t } = useI18n();
  const map = useMap();
  return (
    <div className="absolute bottom-4 right-4 z-[500] flex overflow-hidden rounded-md border bg-background shadow-sm">
      <Button
        variant="ghost"
        size="icon"
        className="rounded-none border-r"
        onClick={() => map.zoomIn()}
      >
        <Plus />
        <span className="sr-only">{t("map.zoomIn")}</span>
      </Button>
      <Button
        variant="ghost"
        size="icon"
        className="rounded-none"
        onClick={() => map.zoomOut()}
      >
        <Minus />
        <span className="sr-only">{t("map.zoomOut")}</span>
      </Button>
    </div>
  );
}

export default function WorldMapView() {
  const { t } = useI18n();
  const navigate = useNavigate();
  const playersQuery = useOnlinePlayers();
  const guildsQuery = useGuilds();
  const serverQuery = useServerInfo();
  const [coordinates, setCoordinates] = useState<readonly [number, number]>([
    0, 0,
  ]);
  const [layers, setLayers] = useState({
    players: true,
    camps: true,
    towers: false,
    fastTravel: false,
  });

  const icons = useMemo(
    () => ({
      player: icon({
        iconUrl: playerIconUrl,
        iconSize: [38, 38],
        iconAnchor: [19, 38],
        tooltipAnchor: [0, -32],
      }),
      camp: icon({
        iconUrl: baseIconUrl,
        iconSize: [46, 46],
        iconAnchor: [23, 42],
      }),
      tower: icon({
        iconUrl: bossTowerIconUrl,
        iconSize: [38, 38],
        iconAnchor: [19, 36],
      }),
      fastTravel: icon({
        iconUrl: fastTravelIconUrl,
        iconSize: [34, 34],
        iconAnchor: [17, 32],
      }),
    }),
    [],
  );

  const toggleLayer = (key: keyof typeof layers, checked: boolean) => {
    setLayers((current) => ({ ...current, [key]: checked }));
  };

  return (
    <div className="relative h-[calc(100dvh-11rem)] min-h-[520px] overflow-hidden lg:h-[calc(100dvh-7rem)]">
      <MapContainer
        crs={CRS.Simple}
        center={[-256, 256]}
        zoom={1}
        minZoom={0}
        maxZoom={8}
        zoomControl={false}
        attributionControl={false}
        maxBounds={[
          [-512, 0],
          [0, 512],
        ]}
        className="h-full w-full"
      >
        <TileLayer
          url="/map/tiles/{z}/{x}/{y}.webp"
          tileSize={512}
          maxNativeZoom={4}
          noWrap
          bounds={[
            [-512, 0],
            [0, 512],
          ]}
        />

        {layers.fastTravel
          ? points.fast_travel.map((point, index) => (
              <Marker
                key={`fast-${index}-${point[0]}-${point[1]}`}
                position={toMapPosition(point)}
                icon={icons.fastTravel}
              />
            ))
          : null}

        {layers.towers
          ? points.boss_tower.map((point, index) => (
              <Marker
                key={`tower-${index}-${point[0]}-${point[1]}`}
                position={toMapPosition(point)}
                icon={icons.tower}
              />
            ))
          : null}

        {layers.players
          ? (playersQuery.data ?? [])
              .filter(
                (player) => player.location_x !== 0 || player.location_y !== 0,
              )
              .map((player) => (
                <Marker
                  key={player.player_uid}
                  position={toMapPosition([
                    player.location_x,
                    player.location_y,
                  ])}
                  icon={icons.player}
                  eventHandlers={{
                    click: () =>
                      navigate(
                        `/players?player=${encodeURIComponent(player.player_uid)}`,
                      ),
                  }}
                >
                  <Tooltip permanent direction="top" opacity={0.95}>
                    {player.nickname}
                  </Tooltip>
                </Marker>
              ))
          : null}

        {layers.camps
          ? (guildsQuery.data ?? []).flatMap((guild) =>
              guild.base_camp.map((camp, index) => (
                <Fragment key={`${guild.admin_player_uid}-${camp.id || index}`}>
                  <Marker
                    position={toMapPosition([camp.location_x, camp.location_y])}
                    icon={icons.camp}
                  >
                    <Popup>
                      <div className="min-w-48 space-y-2">
                        <p className="font-semibold">{guild.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {guild.players.length} {t("guilds.members")} · Lv.
                          {guild.base_camp_level}
                        </p>
                        <Button
                          size="sm"
                          className="w-full"
                          onClick={() =>
                            navigate(
                              `/guilds?guild=${encodeURIComponent(guild.admin_player_uid)}`,
                            )
                          }
                        >
                          {t("action.view")}
                        </Button>
                      </div>
                    </Popup>
                  </Marker>
                  <Circle
                    center={toMapPosition([camp.location_x, camp.location_y])}
                    radius={toMapDistance(camp.area)}
                    pathOptions={{
                      color: "#168c96",
                      fillColor: "#168c96",
                      fillOpacity: 0.08,
                      weight: 1,
                    }}
                  />
                </Fragment>
              )),
            )
          : null}

        <CoordinateTracker onMove={setCoordinates} />
        <MapZoomControls />
      </MapContainer>

      <div className="pointer-events-none absolute inset-x-0 top-0 z-[600] flex items-start justify-between gap-3 p-3 sm:p-4">
        <div className="pointer-events-auto max-w-[calc(100%-3.5rem)] rounded-md border bg-background/94 px-4 py-3 shadow-sm backdrop-blur-sm">
          <div className="flex items-center gap-2">
            <MapPinned className="size-4 text-primary" />
            <h1 className="text-sm font-semibold">{t("map.title")}</h1>
            <Badge variant="outline" className="hidden sm:inline-flex">
              <StatusDot online={serverQuery.isSuccess} />
              {serverQuery.data?.name || "Palworld"}
            </Badge>
          </div>
          <p className="mt-1 hidden text-xs text-muted-foreground sm:block">
            {t("map.subtitle")}
          </p>
        </div>

        <div className="pointer-events-auto rounded-md border bg-background/94 p-2 shadow-sm backdrop-blur-sm">
          <div className="mb-2 flex items-center gap-2 px-1 text-xs font-semibold">
            <Layers3 className="size-4" />
            <span className="hidden sm:inline">{t("map.layers")}</span>
          </div>
          <div className="grid gap-2 sm:min-w-36">
            {(
              [
                ["players", "map.players"],
                ["camps", "map.camps"],
                ["towers", "map.towers"],
                ["fastTravel", "map.fastTravel"],
              ] as const
            ).map(([key, label]) => (
              <Label
                key={key}
                className="flex items-center gap-2 text-xs font-normal"
              >
                <Checkbox
                  checked={layers[key]}
                  onCheckedChange={(checked) =>
                    toggleLayer(key, checked === true)
                  }
                />
                <span className="hidden sm:inline">{t(label)}</span>
              </Label>
            ))}
          </div>
        </div>
      </div>

      <div className="pointer-events-none absolute bottom-4 left-3 z-[600] sm:left-4">
        <div className="flex items-center gap-2 rounded-md border bg-background/94 px-3 py-2 shadow-sm backdrop-blur-sm">
          <LocateFixed className="size-4 text-[var(--signal)]" />
          <span className="font-data text-xs">
            X {formatCoordinate(coordinates[0])} / Y{" "}
            {formatCoordinate(coordinates[1])}
          </span>
        </div>
      </div>
    </div>
  );
}

// web/src/views/PcHome/component/MapView.vue
<script setup>
import "leaflet/dist/leaflet.css";
import {
  LCircle,
  LIcon,
  LMap,
  LMarker,
  LPopup,
  LTileLayer,
  LTooltip,
} from "@vue-leaflet/vue-leaflet";
import { AddCircle20Filled, SubtractCircle20Filled } from "@vicons/fluent";
import ApiService from "@/service/api.js";
import IconBase from "@/assets/map/base.webp";
import IconPlayer from "@/assets/map/player.webp";
import IconBossTower from "@/assets/map/boss_tower.webp";
import IconFastTravel from "@/assets/map/fast_travel.webp";
import playerToGuildStore from "@/stores/model/playerToGuild.js";
import points from "@/assets/map/points.json";

const LANDSCAPE = {
  maxX: 349400,
  maxY: 724400,
  minX: -1099400,
  minY: -724400,
};
const MAP_SIZE = 512;
const MAX_ZOOM = 8;
const MAX_NATIVE_ZOOM = 4;

const api = new ApiService();

const mousePosition = ref([0, 0]);
const zoom = ref(1);
const tiles = ref("map/tiles/{z}/{x}/{y}.webp");
const playerList = ref([]);
const guildList = ref([]);
const showPlayer = ref(true);
const showBaseCamp = ref(true);
const showBossTower = ref(false);
const showFastTravel = ref(false);

let timer = null;

const toMapPosition = (position) => {
  const x =
    -MAP_SIZE +
    (MAP_SIZE * (position[0] - LANDSCAPE.minX)) /
      (LANDSCAPE.maxX - LANDSCAPE.minX);
  const y =
    (MAP_SIZE * (position[1] - LANDSCAPE.minY)) /
    (LANDSCAPE.maxY - LANDSCAPE.minY);
  return [x, y];
};

const toMapDistance = (distance) => {
  return MAP_SIZE * (distance / (LANDSCAPE.maxX - LANDSCAPE.minX));
};

const fromMapPosition = (position) => {
  const x =
    ((position[0] + MAP_SIZE) * (LANDSCAPE.maxX - LANDSCAPE.minX)) / MAP_SIZE +
    LANDSCAPE.minX;
  const y =
    (position[1] * (LANDSCAPE.maxY - LANDSCAPE.minY)) / MAP_SIZE +
    LANDSCAPE.minY;
  return [x.toFixed(0), y.toFixed(0)];
};

const ToPlayers = async (uid) => {
  playerToGuildStore().setCurrentUid(uid);
  playerToGuildStore().setUpdateStatus("players");
};

const refreshPlayer = async () => {
  const { data } = await api.getOnlinePlayerList();
  for (const i of data.value) {
    for (const j of playerList.value) {
      if (i.player_uid === j.player_uid) {
        j.location_x = i.location_x;
        j.location_y = i.location_y;
        break;
      }
    }
  }
  timer = setTimeout(refreshPlayer, 5000);
};

const onMapMouseMove = (event) => {
  mousePosition.value = fromMapPosition([event.latlng.lat, event.latlng.lng]);
};

// 左下角控件
const onAddZoom = () => {
  if (zoom.value !== MAX_ZOOM) {
    zoom.value += 1;
  }
};
const onSubtractZoom = () => {
  if (zoom.value !== 0) {
    zoom.value -= 1;
  }
};

onMounted(async () => {
  let res = await api.getPlayerList({});
  playerList.value = res.data.value;
  // 接口中玩家location_x和location_y同时为0时，表示玩家不在线，不显示
  playerList.value = playerList.value.filter(
    (i) => i.location_x !== 0 && i.location_y !== 0,
  );
  res = await api.getGuildList();
  guildList.value = res.data.value;

  refreshPlayer();
});

onUnmounted(async () => {
  clearTimeout(timer);
});
</script>

<template>
  <div class="map-view h-full">
    <l-map
      ref="map"
      style="width: 100%; height: 100%"
      crs="Simple"
      v-model:zoom="zoom"
      :use-global-leaflet="false"
      :center="[-256, 256]"
      :min-zoom="0"
      :max-zoom="MAX_ZOOM"
      :options="{ zoomControl: false, attributionControl: false }"
      @mousemove="onMapMouseMove"
    >
      <l-tile-layer
        :url="tiles"
        no-wrap
        layer-type="base"
        :options="{
          bounds: [
            [0, 0],
            [-MAP_SIZE, MAP_SIZE],
          ],
          tileSize: 512,
          maxNativeZoom: MAX_NATIVE_ZOOM,
        }"
      ></l-tile-layer>
      <template v-if="showFastTravel">
        <l-marker
          v-for="(point, index) in points.fast_travel"
          :key="`fast-travel-${index}-${point[0]}-${point[1]}`"
          :lat-lng="toMapPosition([point[0], point[1]])"
        >
          <l-icon :icon-url="IconFastTravel" :icon-size="[48, 48]" />
        </l-marker>
      </template>
      <template v-if="showBossTower">
        <l-marker
          v-for="(point, index) in points.boss_tower"
          :key="`boss-tower-${index}-${point[0]}-${point[1]}`"
          :lat-lng="toMapPosition([point[0], point[1]])"
        >
          <l-icon :icon-url="IconBossTower" :icon-size="[48, 48]" />
        </l-marker>
      </template>
      <template v-if="showPlayer">
        <l-marker
          v-for="(player, index) in playerList"
          :key="player.user_id || player.player_uid || `player-${index}`"
          :lat-lng="toMapPosition([player.location_x, player.location_y])"
        >
          <l-icon :icon-url="IconPlayer" :icon-size="[45, 45]" />
          <l-tooltip
            :options="{ direction: 'top', permanent: true, offset: [0, -15] }"
            >{{ player.nickname }}</l-tooltip
          >
        </l-marker>
      </template>
      <template v-if="showBaseCamp">
        <template v-for="guild in guildList" :key="guild.admin_player_uid">
          <template v-for="camp in guild.base_camp" :key="camp.id">
            <l-marker
              :lat-lng="toMapPosition([camp.location_x, camp.location_y])"
            >
              <l-icon :icon-url="IconBase" :icon-size="[55, 55]" />
              <l-popup :options="{ interactive: true }">
                <div style="padding-bottom: 3px; font-size: 16px">
                  {{ $t("map.baseCampTitle", { name: guild.name }) }}
                </div>
                <div style="line-height: 25px">
                  {{ $t("map.guildMember") }}
                  <span
                    v-for="player in guild.players"
                    :key="player.player_uid"
                    class="player_name"
                    @click="ToPlayers(player.player_uid)"
                  >
                    {{ player.nickname }}
                  </span>
                </div>
              </l-popup>
            </l-marker>
            <l-circle
              :lat-lng="toMapPosition([camp.location_x, camp.location_y])"
              :radius="toMapDistance(camp.area)"
            />
          </template>
        </template>
      </template>
    </l-map>
    <div
      class="min-h-50 p-2 fixed bottom-2 left-2 z-999 flex flex-col justify-end"
    >
      <div class="h-40 flex flex-col justify-between items-center">
        <n-icon
          class="cursor-pointer"
          size="24"
          color="#fff"
          @click="onAddZoom"
        >
          <AddCircle20Filled />
        </n-icon>
        <n-slider
          style="height: 100px"
          class="border border-solid border-#fff rounded-full"
          v-model:value="zoom"
          :tooltip="false"
          :height="4"
          :step="1"
          :min="0"
          :max="MAX_ZOOM"
          vertical
        />
        <n-icon
          class="cursor-pointer"
          size="24"
          color="#fff"
          @click="onSubtractZoom"
        >
          <SubtractCircle20Filled />
        </n-icon>
      </div>
    </div>
    <div class="control">
      <div>
        <span>{{ $t("map.showFastTravel") }}</span>
        <n-switch v-model:value="showFastTravel" />
      </div>
      <div>
        <span>{{ $t("map.showBossTower") }}</span>
        <n-switch v-model:value="showBossTower" />
      </div>
      <div>
        <span>{{ $t("map.showPlayer") }}</span>
        <n-switch v-model:value="showPlayer" />
      </div>
      <div>
        <span>{{ $t("map.showBaseCamp") }}</span>
        <n-switch v-model:value="showBaseCamp" />
      </div>
      <div>
        <span>{{ mousePosition[0] }}, {{ mousePosition[1] }}</span>
      </div>
    </div>
  </div>
</template>

<style scoped lang="less">
.leaflet-container {
  background: #102536;
  outline: 0;
}

.player_name {
  margin: 0 3px;
  padding: 3px;
  color: #fff;
  background-color: #009f5d;
  border-radius: 3px;
}

.control {
  width: 200px;
  height: 180px;
  position: absolute;
  bottom: 20px;
  right: 20px;
  color: #fff;
  background-color: rgb(24, 24, 28);
  border-radius: 10px;
  display: flex;
  flex-direction: column;
  justify-content: space-around;
  z-index: 999;
}

.control > div {
  display: flex;
  justify-content: space-between;
  margin: 10px;
}
</style>
